// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yellowtail.Cord.Infrastructure.Persistence;

#nullable disable

namespace Yellowtail.Cord.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CordDbContext))]
    [Migration("20260820182636_RemoveQueryFiltersAndSeedData")]
    partial class RemoveQueryFiltersAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            FirstName = "Alice",
                            LastName = "Smith",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            FirstName = "Bob",
                            LastName = "Johnson",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            FirstName = "Charlie",
                            LastName = "Brown",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            FirstName = "Diana",
                            LastName = "Prince",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            FirstName = "Evan",
                            LastName = "Wright",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            FirstName = "Fiona",
                            LastName = "Gallagher",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666667"),
                            FirstName = "George",
                            LastName = "Clark",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666668"),
                            FirstName = "Hannah",
                            LastName = "Abbott",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666669"),
                            FirstName = "Ian",
                            LastName = "Malcolm",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.MemberSport", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SportId")
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("MemberSports", (string)null);

                    b.HasData(
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666661"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555551")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666662"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555552")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666662"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555553")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666663"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555554")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666664"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666664"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555556")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666665"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555557")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555558")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555559")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666667"),
                            SportId = new Guid("55555555-5555-5555-5555-55555555555a")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666668"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555551")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666668"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555554")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666669"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555552")
                        },
                        new
                        {
                            MemberId = new Guid("66666666-6666-6666-6666-666666666669"),
                            SportId = new Guid("55555555-5555-5555-5555-555555555556")
                        });
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            Description = "Field team sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            Description = "Court team sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            Description = "Racket sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            Description = "Water-based racing",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Track and field",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Athletics"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            Description = "Bicycle racing",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555557"),
                            Description = "Combat sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Boxing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555558"),
                            Description = "Acrobatic sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gymnastics"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555559"),
                            Description = "Court team sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-55555555555a"),
                            Description = "Contact team sport",
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rugby"
                        });
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Default"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Titanium Sports Club"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Apex Athletics Club"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModifiedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Quantum Fitness Club"
                        });
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Member", b =>
                {
                    b.HasOne("Yellowtail.Cord.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Members")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.MemberSport", b =>
                {
                    b.HasOne("Yellowtail.Cord.Domain.Entities.Member", "Member")
                        .WithMany("MemberSports")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yellowtail.Cord.Domain.Entities.Sport", "Sport")
                        .WithMany("MemberSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberSports");
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Sport", b =>
                {
                    b.Navigation("MemberSports");
                });

            modelBuilder.Entity("Yellowtail.Cord.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
